### ISSUE TITLE
Nested property access doesn't appear to work

### ISSUE THREAD

**Issue by benswinburne** [lamansky/conscript.js#1]
This example from the documentation

```
const vars = {
  obj: {a: 1},
}
conscript('obj.a=1')(vars) // true
```

Results in 

```
TypeError: Cannot retrieve property `a` from a non-object
at accessProp (/[...]/node_modules/conscript/index.js:95:11)
```

Presumably either the documentation is incorrect or there's a bug?

**Comment by benswinburne** [comment]
Having looked at the tests, it appears as if you need to use the following var structure

```
  const vars = {
    vars: {
      obj: { a: 1 },
    },
  };
  conscript('obj.a=1')(vars); // true
```

Note the nested vars property.

Not sure whether the docs or the code/tests are wrong? Presumably the docs although the API in the docs is nicer than that in the working code. The nested vars property seems cumbersome.

**Comment by lamansky** [comment]
> Not sure whether the docs or the code/tests are wrong?

You are correct, the readme was inaccurate in several places. Thank you for spotting this and for letting me know.

> The nested vars property seems cumbersome.

I agree, I have found the nested property bothersome also. I just released version 0.1.0 which, among other things, changes the API so that a nested `vars` is no longer used. (This is the only backwards-incompatible change in 0.1.0.)

**Comment by benswinburne** [comment]
Thanks for the quick response and fix.

Assuming you are following semver, perhaps you should bump the major
version given the breaking change?

**Comment by lamansky** [comment]
You're very welcome. Yes, I am following semver. According to [Semantic Versioning 2.0.0](https://semver.org/), breaking changes are permitted under the `0.x` major version. See paragraph 4 of the spec:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by benswinburne** [comment]
Fair enough, I hadn't spotted that clause.

Thanks again for the quick fix!
