### ISSUE TITLE
Wrong compile in 0.2

### ISSUE THREAD

**Issue by vFire** [lamansky/conscript.js#2]
Whick is correctly compiled in 0.1, I used it in the vuejs, and the previous version 0.1 is correct, but currently 0.2 version is wrong ,I use laravel webpack to compile it, it prompt the wrong exists in the last sentense "module.exports = (defaultOptions = {}) => (conscription, options = {}) => conscript(conscription, {...defaultOptions, ...options})" ...

**Comment by lamansky** [comment]
Could you please post the exact error message that webpack gives you when you try to compile?

**Comment by vFire** [comment]
```
ERROR in ./node_modules/conscript/index.js
Module parse failed: Unexpected token (352:99)
You may need an appropriate loader to handle this file type.
| })
|
| module.exports = (defaultOptions = {}) => (conscription, options = {}) => conscript(conscription, {...defaultOptions, ...options})
|
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/js/components/Form/DefaultField.vue 36:16-36
 @ ./resources/js/components/Form/DefaultField.vue
```

**Comment by lamansky** [comment]
What version of Node are you using?

**Comment by vFire** [comment]
V10

**Comment by vFire** [comment]
By the way, please add the "_" to the alphanumeric 
`const alphanumeric = /[a-zA-Z0-9_]/`

I have tested it , it work without any problem, and I really need it to be included.

**Comment by lamansky** [comment]
Try git-cloning the conscript.js repository and running `npm test`. If it works, then the compile error is a problem with your project's configuration, rather than conscript itself.

Try reading [this blog post](http://blog.timwheeler.io/webpack-and/) or [this issue](https://github.com/babel/babel-loader/issues/173) for troubleshooting tips.

Your suggestion is a good idea: I will add the underscore to the alphanumeric rule.

**Comment by vFire** [comment]
thanks
I'll test it later.

**Comment by lamansky** [comment]
I committed the underscore change to the master branch. It will be included in the next release.

If you find that conscript's `npm test` doesn't work on your machine, please reopen this ticket or submit a new one, together with the error message.
