### ISSUE TITLE
Escaping values?

### ISSUE THREAD

**Issue by benswinburne** [lamansky/conscript.js#3]
Is it possible to escape particular characters (Quotes particularly)

For example, I have a user input a value which may be `"ben's food"` and then later I need to use conscript to test a basic expression against that value.

```
const conscript = require("conscript")();

const when = '${var} ~= "\"ben \'s food\""';

const pool = {
  var: '"ben\'s food"',
};

const out = conscript(String(when))(pool);

console.log(out); // false
```

I can't seem to get escaping working. Is this supported and i'm just doing it wrong or is it not supported?

Thanks

**Comment by lamansky** [comment]
It's supported. There's just an error in your JavaScript. You need to double-escape your double quotation marks, like so:

`const when = '${var} ~= "\\"ben \'s food\\""';`

Your code told JavaScript to escape the quotation marks, which it did, and so Conscript never got to see the backslashes. This is the string that you were passing to Conscript:

`${var} ~= ""ben 's food""`

Conscript saw the double quotation marks (`""`) at the beginning and interpreted it as a test for an empty string, which is not what you want. If you escape your backslashes, then JavaScript will send the backslashes to Conscript.
